##################################################################################################
# Productpage service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: productpage
  labels:
    app: productpage
    service: productpage
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: productpage
##################################################################################################
# Productpage deployment
##################################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage
  labels:
    app: productpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
  template:
    metadata:
      labels:
        app: productpage
    spec:
      containers:
        - env:
          image: patriciaortuno28/practica-creativa2:28productpage
          name: 28-productpage
          ports:
            - containerPort: 9080
          resources: {}
      restartPolicy: Always
